-- =====================================================
-- MÓDULO DE CONTROL SANITARIO DE BOVINOS
-- =====================================================
-- Este script extiende el schema existente con tablas
-- para gestionar vacunaciones, preñez, visitas veterinarias
-- y recordatorios automáticos.
-- =====================================================

BEGIN;

-- =====================================================
-- 1. PLANES DE VACUNACIÓN
-- =====================================================
-- Tabla para definir planes de vacunación generales
-- Ejemplo: "Aftosa Triple Mayo-Junio 2024"

CREATE TABLE IF NOT EXISTS public.ttrplanvacun
(
    ttr_idplanva INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_nomplan VARCHAR(100) NOT NULL,
    ttr_idtipvac INTEGER NOT NULL,
    ttr_fechaini DATE NOT NULL,
    ttr_fechafin DATE NOT NULL,
    ttr_intervalo INTEGER,                    -- Días entre dosis (si aplica)
    ttr_numdosis INTEGER DEFAULT 1,           -- Número de dosis del plan
    ttr_descripcion TEXT,
    ttr_activo BOOLEAN DEFAULT TRUE,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ttr_fechupda TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrplanvacun_pkey PRIMARY KEY (ttr_idplanva),
    CONSTRAINT fk_planvacun_tipvac FOREIGN KEY (ttr_idtipvac)
        REFERENCES public.tmatipvacun (tma_idtipva) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- =====================================================
-- 2. VACUNACIONES APLICADAS
-- =====================================================
-- Registro de vacunas aplicadas a bovinos individuales
-- con cálculo automático de próximas fechas

CREATE TABLE IF NOT EXISTS public.ttrvacunacion
(
    ttr_idvacuna INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idbovino INTEGER NOT NULL,
    ttr_idplanva INTEGER,                     -- Opcional: asociar a un plan
    ttr_idtipvac INTEGER NOT NULL,
    ttr_fechaapl DATE NOT NULL,               -- Fecha de aplicación
    ttr_proxfech DATE,                        -- Próxima fecha calculada
    ttr_numdosis INTEGER DEFAULT 1,           -- Número de dosis (1, 2, 3...)
    ttr_idempldo INTEGER,                     -- Empleado que aplicó
    ttr_lote VARCHAR(50),                     -- Lote de la vacuna
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrvacunacion_pkey PRIMARY KEY (ttr_idvacuna),
    CONSTRAINT fk_vacunacion_bovino FOREIGN KEY (ttr_idbovino)
        REFERENCES public.ttrbovinoss (ttr_idbovino) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_vacunacion_plan FOREIGN KEY (ttr_idplanva)
        REFERENCES public.ttrplanvacun (ttr_idplanva) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT fk_vacunacion_tipvac FOREIGN KEY (ttr_idtipvac)
        REFERENCES public.tmatipvacun (tma_idtipva) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_vacunacion_empleado FOREIGN KEY (ttr_idempldo)
        REFERENCES public.ttrempleado (ttr_idemplo) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

-- =====================================================
-- 3. CONTROL DE PREÑEZ
-- =====================================================
-- Registro de preñeces de las vacas

CREATE TABLE IF NOT EXISTS public.ttrprenez
(
    ttr_idprenez INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idbovino INTEGER NOT NULL,
    ttr_fechaini DATE NOT NULL,               -- Fecha estimada inicio preñez
    ttr_fechaestp DATE,                       -- Fecha estimada de parto
    ttr_fechareal DATE,                       -- Fecha real de parto
    ttr_estadopre VARCHAR(50),                -- Confirmada, En proceso, Finalizada
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ttr_fechupda TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrprenez_pkey PRIMARY KEY (ttr_idprenez),
    CONSTRAINT fk_prenez_bovino FOREIGN KEY (ttr_idbovino)
        REFERENCES public.ttrbovinoss (ttr_idbovino) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

-- =====================================================
-- 4. TRATAMIENTOS DE PREÑEZ
-- =====================================================
-- Tratamientos asociados a preñez (mastitis, post-parto, etc.)

CREATE TABLE IF NOT EXISTS public.ttrtratprenez
(
    ttr_idtratpr INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idprenez INTEGER NOT NULL,
    ttr_idtratam INTEGER,
    ttr_fechaapl DATE NOT NULL,
    ttr_tipotrat VARCHAR(100),                -- Mastitis, Post-parto, Suero, Calcio, etc.
    ttr_proxfech DATE,                        -- Próxima aplicación
    ttr_dosisnum INTEGER DEFAULT 1,
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrtratprenez_pkey PRIMARY KEY (ttr_idtratpr),
    CONSTRAINT fk_tratprenez_prenez FOREIGN KEY (ttr_idprenez)
        REFERENCES public.ttrprenez (ttr_idprenez) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_tratprenez_trat FOREIGN KEY (ttr_idtratam)
        REFERENCES public.tmatratamen (tma_idtrata) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

-- =====================================================
-- 5. VISITAS VETERINARIAS
-- =====================================================
-- Registro de visitas veterinarias trimestrales

CREATE TABLE IF NOT EXISTS public.ttrvisivete
(
    ttr_idvisvet INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_fechavis DATE NOT NULL,
    ttr_proxfech DATE,                        -- Próxima visita (+3 meses)
    ttr_veterina VARCHAR(200),                -- Nombre del veterinario
    ttr_telefono VARCHAR(15),
    ttr_motivovi TEXT,                        -- Chequeo reproductivo, emergencia, etc.
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ttr_fechupda TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrvisivete_pkey PRIMARY KEY (ttr_idvisvet)
);

-- =====================================================
-- 6. BOVINOS REVISADOS EN VISITA VETERINARIA
-- =====================================================
-- Tabla intermedia: bovinos revisados en cada visita

CREATE TABLE IF NOT EXISTS public.ttrvisibovino
(
    ttr_idvisbov INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idvisvet INTEGER NOT NULL,
    ttr_idbovino INTEGER NOT NULL,
    ttr_diagnos TEXT,
    ttr_tratamie TEXT,
    ttr_estadore VARCHAR(100),                -- Gestante, Vacía, Post-parto, etc.
    ttr_observa TEXT,
    CONSTRAINT ttrvisibovino_pkey PRIMARY KEY (ttr_idvisbov),
    CONSTRAINT fk_visibovino_visita FOREIGN KEY (ttr_idvisvet)
        REFERENCES public.ttrvisivete (ttr_idvisvet) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_visibovino_bovino FOREIGN KEY (ttr_idbovino)
        REFERENCES public.ttrbovinoss (ttr_idbovino) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

-- =====================================================
-- DATOS INICIALES
-- =====================================================
-- Insertar tipos de vacunas comunes si no existen

INSERT INTO public.tmatipvacun (tma_nomtipv) VALUES 
    ('Aftosa Triple'),
    ('Aftosa + Clostridium'),
    ('Estomatitis'),
    ('Mastitis'),
    ('Brucelosis'),
    ('Rabia'),
    ('Carbón Sintomático'),
    ('IBR/DVB'),
    ('Leptospirosis')
ON CONFLICT DO NOTHING;

-- =====================================================
-- ÍNDICES PARA OPTIMIZACIÓN
-- =====================================================

-- Índices para búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_vacunacion_bovino ON public.ttrvacunacion(ttr_idbovino);
CREATE INDEX IF NOT EXISTS idx_vacunacion_proxfech ON public.ttrvacunacion(ttr_proxfech);
CREATE INDEX IF NOT EXISTS idx_vacunacion_fechaapl ON public.ttrvacunacion(ttr_fechaapl);

CREATE INDEX IF NOT EXISTS idx_prenez_bovino ON public.ttrprenez(ttr_idbovino);
CREATE INDEX IF NOT EXISTS idx_prenez_estado ON public.ttrprenez(ttr_estadopre);

CREATE INDEX IF NOT EXISTS idx_tratprenez_prenez ON public.ttrtratprenez(ttr_idprenez);
CREATE INDEX IF NOT EXISTS idx_tratprenez_proxfech ON public.ttrtratprenez(ttr_proxfech);

CREATE INDEX IF NOT EXISTS idx_visivete_fechavis ON public.ttrvisivete(ttr_fechavis);
CREATE INDEX IF NOT EXISTS idx_visivete_proxfech ON public.ttrvisivete(ttr_proxfech);

CREATE INDEX IF NOT EXISTS idx_visibovino_bovino ON public.ttrvisibovino(ttr_idbovino);

COMMIT;

-- =====================================================
-- FIN DEL SCRIPT
-- =====================================================
