-- =====================================================
-- MASTER SCHEMA - SISTEMA FINCA LA LAGUNA
-- =====================================================
-- Fecha Consolidación: 2026-01-25
-- Contenido:
-- 1. Tablas Base (Usuarios, Empleados, Config)
-- 2. Módulos: Bovinos, Producción, Potreros, Ventas, Sanidad
-- 3. Actualizaciones y Parches
-- =====================================================

BEGIN;

-- =====================================================
-- 1. TABLAS BASE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tmacatinsum (
    tma_idcatin INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomcati character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmacatinsum_pkey PRIMARY KEY (tma_idcatin)
);

CREATE TABLE IF NOT EXISTS public.tmacolbovin (
    tma_idcolbo INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomcolb character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmacolbovin_pkey PRIMARY KEY (tma_idcolbo)
);

CREATE TABLE IF NOT EXISTS public.tmaempleado (
    tma_idemplo INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nombrel character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT tmaempleado_pkey PRIMARY KEY (tma_idemplo)
);

CREATE TABLE IF NOT EXISTS public.tmaestbovin (
    tma_idestbo INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomestb character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmaestbovin_pkey PRIMARY KEY (tma_idestbo)
);

CREATE TABLE IF NOT EXISTS public.tmaestfactu (
    tma_idestfa INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomestf character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmaestfactu_pkey PRIMARY KEY (tma_idestfa)
);

CREATE TABLE IF NOT EXISTS public.tmaestpotre (
    tma_idestpo INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomestp character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmaestpotre_pkey PRIMARY KEY (tma_idestpo)
);

CREATE TABLE IF NOT EXISTS public.tmaetabovin (
    tma_idetabo INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nometab character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmaetabovin_pkey PRIMARY KEY (tma_idetabo)
);

CREATE TABLE IF NOT EXISTS public.tmalotes (
    tma_idlote INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomlote character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT tmalotes_pkey PRIMARY KEY (tma_idlote)
);

CREATE TABLE IF NOT EXISTS public.tmarazabovi (
    tma_idrazab INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomraza character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmarazabovi_pkey PRIMARY KEY (tma_idrazab)
);

CREATE TABLE IF NOT EXISTS public.tmarolusuar (
    tma_idrolus INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomrolu character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmarolusuar_pkey PRIMARY KEY (tma_idrolus)
);

CREATE TABLE IF NOT EXISTS public.tmatipcomp (
    tma_idtipcom INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomtipc character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmatipcomp_pkey PRIMARY KEY (tma_idtipcom)
);

CREATE TABLE IF NOT EXISTS public.tmatipmante (
    tma_idtipma INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomtipm character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmatipmante_pkey PRIMARY KEY (tma_idtipma)
);

CREATE TABLE IF NOT EXISTS public.tmatipmovim (
    tma_idtipmo INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomtipm character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmatipmovim_pkey PRIMARY KEY (tma_idtipmo)
);

CREATE TABLE IF NOT EXISTS public.tmatippagos (
    tma_idtippag INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomtipp character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmatippagos_pkey PRIMARY KEY (tma_idtippag)
);

CREATE TABLE IF NOT EXISTS public.tmatipvacun (
    tma_idtipva INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomtipv character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmatipvacun_pkey PRIMARY KEY (tma_idtipva)
);

CREATE TABLE IF NOT EXISTS public.tmatipventa (
    tma_idtipve INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomtipv character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmatipventa_pkey PRIMARY KEY (tma_idtipve)
);

CREATE TABLE IF NOT EXISTS public.tmatratamen (
    tma_idtrata INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomtrat character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tmatratamen_pkey PRIMARY KEY (tma_idtrata)
);

CREATE TABLE IF NOT EXISTS public.ttrasistenc (
    ttr_idasisen INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idemplea integer,
    ttr_horaentr time without time zone,
    ttr_horasali time without time zone,
    ttr_horatrab time without time zone,
    ttr_fechaasi date,
    ttr_idtipasi integer DEFAULT 1,
    CONSTRAINT ttrasistenc_pkey PRIMARY KEY (ttr_idasisen)
);

CREATE TABLE IF NOT EXISTS public.tmatipasist (
    tma_idtipasi INT GENERATED BY DEFAULT AS IDENTITY,
    tma_nomtipa character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tmatipasist_pkey PRIMARY KEY (tma_idtipasi),
    CONSTRAINT tmatipasist_tma_nomtipa_key UNIQUE (tma_nomtipa)
);

CREATE TABLE IF NOT EXISTS public.ttrbovinoss (
    ttr_idbovino INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_numerobv integer,
    ttr_idrazabo integer,
    ttr_fecnacim date,
    ttr_idcolorb integer,
    ttr_pesokilo double precision,
    ttr_idetapav integer,
    ttr_idestadb integer,
    CONSTRAINT ttrbovinoss_pkey PRIMARY KEY (ttr_idbovino)
);

CREATE TABLE IF NOT EXISTS public.ttrclienteee (
    ttr_idclient INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_nomcompa character varying(100) COLLATE pg_catalog."default",
    ttr_nombrecl character varying(100) COLLATE pg_catalog."default",
    ttr_apellido character varying(100) COLLATE pg_catalog."default",
    ttr_documecl character varying(8) COLLATE pg_catalog."default",
    ttr_telefono character varying(11) COLLATE pg_catalog."default",
    ttr_direccio text COLLATE pg_catalog."default",
    ttr_correocl character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT ttrclienteee_pkey PRIMARY KEY (ttr_idclient)
);

CREATE TABLE IF NOT EXISTS public.ttregresoss (
    ttr_idegreso INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idempreg integer,
    ttr_fechpago date,
    ttr_idtippag integer,
    ttr_idnomref integer,
    ttr_idpagref integer,
    ttr_fechcrea timestamp without time zone,
    ttr_fechupda timestamp without time zone,
    CONSTRAINT ttregresoss_pkey PRIMARY KEY (ttr_idegreso)
);

CREATE TABLE IF NOT EXISTS public.ttrempleado (
    ttr_idemplo INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_nombrel character varying(100) COLLATE pg_catalog."default",
    ttr_apellid character varying(100) COLLATE pg_catalog."default",
    ttr_documen character varying(8) COLLATE pg_catalog."default",
    ttr_fecnaci date,
    ttr_telefon character varying(11) COLLATE pg_catalog."default",
    ttr_direcci text COLLATE pg_catalog."default",
    ttr_feccont date,
    ttr_idcargp integer,
    ttr_feccrea timestamp without time zone,
    ttr_fecupda timestamp without time zone,
    ttr_estado character varying(20) DEFAULT 'ACTIVO',
    CONSTRAINT ttrempleado_pkey PRIMARY KEY (ttr_idemplo)
);

CREATE TABLE IF NOT EXISTS public.ttrfacturas (
    ttr_idfactur INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idclient integer,
    ttr_idusuref integer,
    ttr_idprodct integer,
    ttr_fechafac timestamp without time zone,
    ttr_idtipven integer,
    ttr_litrosfc double precision,
    ttr_idregmdc integer,
    ttr_idestfac integer,
    ttr_montofac double precision,
    ttr_idtipcom integer,
    CONSTRAINT ttrfacturas_pkey PRIMARY KEY (ttr_idfactur)
);

CREATE TABLE IF NOT EXISTS public.ttrinsumoso (
    ttr_idinsumo INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idcatein integer,
    ttr_nominsum character varying(100) COLLATE pg_catalog."default",
    ttr_cantidad integer,
    ttr_fechaven date,
    CONSTRAINT ttrinsumoso_pkey PRIMARY KEY (ttr_idinsumo)
);

CREATE TABLE IF NOT EXISTS public.ttrlotpotr (
    ttr_idlotpot INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idpotrer integer,
    ttr_idlote integer,
    ttr_fechaasi date,
    CONSTRAINT ttrlotpotr_pkey PRIMARY KEY (ttr_idlotpot)
);

CREATE TABLE IF NOT EXISTS public.ttrmovimien (
    ttr_idmovime INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idinsumo integer,
    ttr_idtipmov integer,
    ttr_cantimov integer,
    ttr_fechamov timestamp without time zone,
    ttr_fechcrea timestamp without time zone,
    ttr_fechupda timestamp without time zone,
    CONSTRAINT ttrmovimien_pkey PRIMARY KEY (ttr_idmovime)
);

CREATE TABLE IF NOT EXISTS public.ttrnominass (
    ttr_idnomina INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idasiste integer,
    ttr_tothoras double precision,
    ttr_totpagos double precision,
    ttr_fechaini date,
    ttr_fechafin date,
    ttr_fechcrea timestamp without time zone,
    CONSTRAINT ttrnominass_pkey PRIMARY KEY (ttr_idnomina)
);

CREATE TABLE IF NOT EXISTS public.ttrpaginsum (
    ttr_idpagins INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idinsump integer,
    ttr_montopag double precision,
    ttr_fechapag timestamp without time zone,
    ttr_fechcrea timestamp without time zone,
    ttr_fechupda timestamp without time zone,
    CONSTRAINT ttrpaginsum_pkey PRIMARY KEY (ttr_idpagins)
);

CREATE TABLE IF NOT EXISTS public.ttrpotreros (
    ttr_idpotrer INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_codpotre character varying(20) COLLATE pg_catalog."default",
    ttr_idestpot integer,
    ttr_idtipman integer,
    ttr_fechamnt date,
    ttr_descripc text COLLATE pg_catalog."default",
    CONSTRAINT ttrpotreros_pkey PRIMARY KEY (ttr_idpotrer)
);

CREATE TABLE IF NOT EXISTS public.ttrprodlech (
    ttr_idprodlc INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idbovlec integer,
    ttr_idlote integer,
    ttr_idprolot integer,
    ttr_fechapro date,
    ttr_litrsprd double precision,
    ttr_fechcrea timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ttr_fechupda timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrprodlech_pkey PRIMARY KEY (ttr_idprodlc)
);

CREATE TABLE IF NOT EXISTS public.ttrprodLOTE (
    ttr_idprolot INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idlote integer,
    ttr_fechapro date,
    ttr_totlitrs double precision,
    ttr_fechcrea timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ttr_fechupda timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrprodLOTE_pkey PRIMARY KEY (ttr_idprolot)
);

CREATE TABLE IF NOT EXISTS public.ttrregmedic (
    ttr_idregmed INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idempmed integer,
    ttr_idmovref integer,
    ttr_diagnost text COLLATE pg_catalog."default",
    ttr_idtratam integer,
    ttr_idvacuna integer,
    ttr_fechareg timestamp without time zone,
    CONSTRAINT ttrregmedic_pkey PRIMARY KEY (ttr_idregmed)
);

CREATE TABLE IF NOT EXISTS public.ttrusuarioo (
    ttr_idusuar INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_nombrel character varying(100) COLLATE pg_catalog."default",
    ttr_apellid character varying(100) COLLATE pg_catalog."default",
    ttr_correoe character varying(100) COLLATE pg_catalog."default",
    ttr_contrasena character varying(255) COLLATE pg_catalog."default",
    ttr_telefon character varying(11) COLLATE pg_catalog."default",
    ttr_idrolus integer,
    ttr_token character varying(255) COLLATE pg_catalog."default",
    ttr_estado character varying(20) DEFAULT 'ACTIVO',
    CONSTRAINT ttrusuarioo_pkey PRIMARY KEY (ttr_idusuar)
);

CREATE TABLE IF NOT EXISTS public.ttrregmedbovinos (
    ttr_idregmed_fk integer NOT NULL,
    ttr_idbovino_fk integer NOT NULL,
    CONSTRAINT ttrregmedbovinos_pkey PRIMARY KEY (ttr_idregmed_fk, ttr_idbovino_fk)
);

CREATE TABLE IF NOT EXISTS public.ttrbovlotpotr (
    ttr_idbovlotpot INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idbovino integer NOT NULL,
    ttr_idlote integer NOT NULL,
    ttr_idpotrer integer NOT NULL,
    ttr_fechaini date NOT NULL,
    ttr_fechafin date,
    ttr_fechcrea timestamp without time zone,
    ttr_fechupda timestamp without time zone,
    CONSTRAINT ttrbovlotpotr_pkey PRIMARY KEY (ttr_idbovlotpot)
);

INSERT INTO public.tmatipasist (tma_idtipasi, tma_nomtipa) VALUES (1, 'Presente') ON CONFLICT (tma_idtipasi) DO NOTHING;
INSERT INTO public.tmatipasist (tma_idtipasi, tma_nomtipa) VALUES (2, 'Ausente') ON CONFLICT (tma_idtipasi) DO NOTHING;
INSERT INTO public.tmatipasist (tma_idtipasi, tma_nomtipa) VALUES (3, 'Reposo') ON CONFLICT (tma_idtipasi) DO NOTHING;
INSERT INTO public.tmatipasist (tma_idtipasi, tma_nomtipa) VALUES (4, 'Pendiente') ON CONFLICT (tma_idtipasi) DO NOTHING;

SELECT setval('public.tmatipasist_tma_idtipasi_seq', (SELECT MAX(tma_idtipasi) FROM public.tmatipasist));

-- FOREIGN KEYS
ALTER TABLE IF EXISTS public.ttrasistenc ADD CONSTRAINT ttrasistenc_ttr_idemplea_fkey FOREIGN KEY (ttr_idemplea) REFERENCES public.ttrempleado (ttr_idemplo);
ALTER TABLE IF EXISTS public.ttrasistenc ADD CONSTRAINT ttrasistenc_ttr_idtipasi_fkey FOREIGN KEY (ttr_idtipasi) REFERENCES public.tmatipasist (tma_idtipasi);
ALTER TABLE IF EXISTS public.ttrbovinoss ADD CONSTRAINT ttrbovinoss_ttr_idcolorb_fkey FOREIGN KEY (ttr_idcolorb) REFERENCES public.tmacolbovin (tma_idcolbo);
ALTER TABLE IF EXISTS public.ttrbovinoss ADD CONSTRAINT ttrbovinoss_ttr_idestadb_fkey FOREIGN KEY (ttr_idestadb) REFERENCES public.tmaestbovin (tma_idestbo);
ALTER TABLE IF EXISTS public.ttrbovinoss ADD CONSTRAINT ttrbovinoss_ttr_idetapav_fkey FOREIGN KEY (ttr_idetapav) REFERENCES public.tmaetabovin (tma_idetabo);
ALTER TABLE IF EXISTS public.ttrbovinoss ADD CONSTRAINT ttrbovinoss_ttr_idrazabo_fkey FOREIGN KEY (ttr_idrazabo) REFERENCES public.tmarazabovi (tma_idrazab);
ALTER TABLE IF EXISTS public.ttregresoss ADD CONSTRAINT ttregresoss_ttr_idempreg_fkey FOREIGN KEY (ttr_idempreg) REFERENCES public.ttrempleado (ttr_idemplo);
ALTER TABLE IF EXISTS public.ttregresoss ADD CONSTRAINT ttregresoss_ttr_idnomref_fkey FOREIGN KEY (ttr_idnomref) REFERENCES public.ttrnominass (ttr_idnomina);
ALTER TABLE IF EXISTS public.ttregresoss ADD CONSTRAINT ttregresoss_ttr_idpagref_fkey FOREIGN KEY (ttr_idpagref) REFERENCES public.ttrpaginsum (ttr_idpagins);
ALTER TABLE IF EXISTS public.ttregresoss ADD CONSTRAINT ttregresoss_ttr_idtippag_fkey FOREIGN KEY (ttr_idtippag) REFERENCES public.tmatippagos (tma_idtippag);
ALTER TABLE IF EXISTS public.ttrempleado ADD CONSTRAINT ttrempleado_ttr_idcargp_fkey FOREIGN KEY (ttr_idcargp) REFERENCES public.tmaempleado (tma_idemplo);
ALTER TABLE IF EXISTS public.ttrfacturas ADD CONSTRAINT ttrfacturas_ttr_idclient_fkey FOREIGN KEY (ttr_idclient) REFERENCES public.ttrclienteee (ttr_idclient);
ALTER TABLE IF EXISTS public.ttrfacturas ADD CONSTRAINT ttrfacturas_ttr_idestfac_fkey FOREIGN KEY (ttr_idestfac) REFERENCES public.tmaestfactu (tma_idestfa);
ALTER TABLE IF EXISTS public.ttrfacturas ADD CONSTRAINT ttrfacturas_ttr_idprodct_fkey FOREIGN KEY (ttr_idprodct) REFERENCES public.ttrprodlech (ttr_idprodlc);
ALTER TABLE IF EXISTS public.ttrfacturas ADD CONSTRAINT ttrfacturas_ttr_idregmdc_fkey FOREIGN KEY (ttr_idregmdc) REFERENCES public.ttrregmedic (ttr_idregmed);
ALTER TABLE IF EXISTS public.ttrfacturas ADD CONSTRAINT ttrfacturas_ttr_idtipcom_fkey FOREIGN KEY (ttr_idtipcom) REFERENCES public.tmatipcomp (tma_idtipcom);
ALTER TABLE IF EXISTS public.ttrfacturas ADD CONSTRAINT ttrfacturas_ttr_idtipven_fkey FOREIGN KEY (ttr_idtipven) REFERENCES public.tmatipventa (tma_idtipve);
ALTER TABLE IF EXISTS public.ttrfacturas ADD CONSTRAINT ttrfacturas_ttr_idusuref_fkey FOREIGN KEY (ttr_idusuref) REFERENCES public.ttrusuarioo (ttr_idusuar);
ALTER TABLE IF EXISTS public.ttrinsumoso ADD CONSTRAINT ttrinsumoso_ttr_idcatein_fkey FOREIGN KEY (ttr_idcatein) REFERENCES public.tmacatinsum (tma_idcatin);
ALTER TABLE IF EXISTS public.ttrlotpotr ADD CONSTRAINT ttrlotpotr_ttr_idlote_fkey FOREIGN KEY (ttr_idlote) REFERENCES public.tmalotes (tma_idlote);
ALTER TABLE IF EXISTS public.ttrlotpotr ADD CONSTRAINT ttrlotpotr_ttr_idpotrer_fkey FOREIGN KEY (ttr_idpotrer) REFERENCES public.ttrpotreros (ttr_idpotrer);
ALTER TABLE IF EXISTS public.ttrmovimien ADD CONSTRAINT ttrmovimien_ttr_idinsumo_fkey FOREIGN KEY (ttr_idinsumo) REFERENCES public.ttrinsumoso (ttr_idinsumo);
ALTER TABLE IF EXISTS public.ttrmovimien ADD CONSTRAINT ttrmovimien_ttr_idtipmov_fkey FOREIGN KEY (ttr_idtipmov) REFERENCES public.tmatipmovim (tma_idtipmo);
ALTER TABLE IF EXISTS public.ttrnominass ADD CONSTRAINT ttrnominass_ttr_idasiste_fkey FOREIGN KEY (ttr_idasiste) REFERENCES public.ttrasistenc (ttr_idasisen);
ALTER TABLE IF EXISTS public.ttrpaginsum ADD CONSTRAINT ttrpaginsum_ttr_idinsump_fkey FOREIGN KEY (ttr_idinsumo) REFERENCES public.ttrinsumoso (ttr_idinsumo);
ALTER TABLE IF EXISTS public.ttrpotreros ADD CONSTRAINT ttrpotreros_ttr_idestpot_fkey FOREIGN KEY (ttr_idestpot) REFERENCES public.tmaestpotre (tma_idestpo);
ALTER TABLE IF EXISTS public.ttrpotreros ADD CONSTRAINT ttrpotreros_ttr_idtipman_fkey FOREIGN KEY (ttr_idtipman) REFERENCES public.tmatipmante (tma_idtipma);
ALTER TABLE IF EXISTS public.ttrprodlech ADD CONSTRAINT ttrprodlech_ttr_idbovlec_fkey FOREIGN KEY (ttr_idbovlec) REFERENCES public.ttrbovinoss (ttr_idbovino);
ALTER TABLE IF EXISTS public.ttrprodlech ADD CONSTRAINT ttrprodlech_ttr_idlote_fkey FOREIGN KEY (ttr_idlote) REFERENCES public.tmalotes (tma_idlote);
ALTER TABLE IF EXISTS public.ttrprodlech ADD CONSTRAINT ttrprodlech_ttr_idprolot_fkey FOREIGN KEY (ttr_idprolot) REFERENCES public.ttrprodLOTE (ttr_idprolot);
ALTER TABLE IF EXISTS public.ttrprodLOTE ADD CONSTRAINT ttrprodLOTE_ttr_idlote_fkey FOREIGN KEY (ttr_idlote) REFERENCES public.tmalotes (tma_idlote);
ALTER TABLE IF EXISTS public.ttrregmedic ADD CONSTRAINT ttrregmedic_ttr_idempmed_fkey FOREIGN KEY (ttr_idempmed) REFERENCES public.ttrempleado (ttr_idemplo);
ALTER TABLE IF EXISTS public.ttrregmedic ADD CONSTRAINT ttrregmedic_ttr_idmovref_fkey FOREIGN KEY (ttr_idmovref) REFERENCES public.ttrmovimien (ttr_idmovime);
ALTER TABLE IF EXISTS public.ttrregmedic ADD CONSTRAINT ttrregmedic_ttr_idtratam_fkey FOREIGN KEY (ttr_idtratam) REFERENCES public.tmatratamen (tma_idtrata);
ALTER TABLE IF EXISTS public.ttrregmedic ADD CONSTRAINT ttrregmedic_ttr_idvacuna_fkey FOREIGN KEY (ttr_idvacuna) REFERENCES public.tmatipvacun (tma_idtipva);
ALTER TABLE IF EXISTS public.ttrusuarioo ADD CONSTRAINT ttrusuarioo_ttr_idrolus_fkey FOREIGN KEY (ttr_idrolus) REFERENCES public.tmarolusuar (tma_idrolus);

ALTER TABLE IF EXISTS public.ttrregmedbovinos ADD CONSTRAINT ttrregmedbovinos_ttr_idbovino_fk_fkey FOREIGN KEY (ttr_idbovino_fk) REFERENCES public.ttrbovinoss (ttr_idbovino) ON DELETE CASCADE;
ALTER TABLE IF EXISTS public.ttrregmedbovinos ADD CONSTRAINT ttrregmedbovinos_ttr_idregmed_fk_fkey FOREIGN KEY (ttr_idregmed_fk) REFERENCES public.ttrregmedic (ttr_idregmed) ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.ttrbovlotpotr ADD CONSTRAINT ttrbovlotpotr_ttr_idbovino_fkey FOREIGN KEY (ttr_idbovino) REFERENCES public.ttrbovinoss (ttr_idbovino);
ALTER TABLE IF EXISTS public.ttrbovlotpotr ADD CONSTRAINT ttrbovlotpotr_ttr_idlote_fkey FOREIGN KEY (ttr_idlote) REFERENCES public.tmalotes (tma_idlote);
ALTER TABLE IF EXISTS public.ttrbovlotpotr ADD CONSTRAINT ttrbovlotpotr_ttr_idpotrer_fkey FOREIGN KEY (ttr_idpotrer) REFERENCES public.ttrpotreros (ttr_idpotrer);

ALTER TABLE IF EXISTS public.ttrempleado ADD CONSTRAINT ttrempleado_ttr_documen_key UNIQUE (ttr_documen);
ALTER TABLE IF EXISTS public.ttrusuarioo ADD CONSTRAINT ttrusuarioo_ttr_correoe_key UNIQUE (ttr_correoe);
ALTER TABLE IF EXISTS public.ttrclienteee ADD CONSTRAINT ttrclienteee_ttr_documecl_key UNIQUE (ttr_documecl);
ALTER TABLE IF EXISTS public.ttrclienteee ADD CONSTRAINT ttrclienteee_ttr_correocl_key UNIQUE (ttr_correocl);
ALTER TABLE IF EXISTS public.ttrbovinoss ADD CONSTRAINT ttrbovinoss_ttr_numerobv_key UNIQUE (ttr_numerobv);

-- =====================================================
-- 2. GESTIÓN AVANZADA DE POTREROS (De schema_potreros.sql)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.ttrhistbovlote
(
    ttr_idhistbl INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idbovino INTEGER NOT NULL,
    ttr_idlote INTEGER NOT NULL,
    ttr_fechaini DATE NOT NULL DEFAULT CURRENT_DATE,
    ttr_fechafin DATE,
    ttr_motivo VARCHAR(100),
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrhistbovlote_pkey PRIMARY KEY (ttr_idhistbl),
    CONSTRAINT fk_histbovlote_bovino FOREIGN KEY (ttr_idbovino) REFERENCES public.ttrbovinoss (ttr_idbovino) ON DELETE CASCADE,
    CONSTRAINT fk_histbovlote_lote FOREIGN KEY (ttr_idlote) REFERENCES public.tmalotes (tma_idlote) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_histbovlote_bovino ON public.ttrhistbovlote(ttr_idbovino);
CREATE INDEX IF NOT EXISTS idx_histbovlote_lote ON public.ttrhistbovlote(ttr_idlote);
CREATE INDEX IF NOT EXISTS idx_histbovlote_fechas ON public.ttrhistbovlote(ttr_fechaini, ttr_fechafin);

CREATE TABLE IF NOT EXISTS public.ttrrotacion
(
    ttr_idrotaci INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idlote INTEGER NOT NULL,
    ttr_idpotrer INTEGER NOT NULL,
    ttr_fecha DATE NOT NULL,
    ttr_turno VARCHAR(20) NOT NULL,
    ttr_alturain DECIMAL(5,2),
    ttr_alturaout DECIMAL(5,2),
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrrotacion_pkey PRIMARY KEY (ttr_idrotaci),
    CONSTRAINT fk_rotacion_lote FOREIGN KEY (ttr_idlote) REFERENCES public.tmalotes (tma_idlote) ON DELETE CASCADE,
    CONSTRAINT fk_rotacion_potrero FOREIGN KEY (ttr_idpotrer) REFERENCES public.ttrpotreros (ttr_idpotrer) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_rotacion_potrero ON public.ttrrotacion(ttr_idpotrer);
CREATE INDEX IF NOT EXISTS idx_rotacion_fecha ON public.ttrrotacion(ttr_fecha);

CREATE TABLE IF NOT EXISTS public.ttrmantepotre
(
    ttr_idmantpo INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idpotrer INTEGER NOT NULL,
    ttr_tipo VARCHAR(50) NOT NULL,
    ttr_fecha DATE NOT NULL,
    ttr_producto VARCHAR(100),
    ttr_cantidad DECIMAL(10,2),
    ttr_observa TEXT,
    ttr_responsable INTEGER,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrmantepotre_pkey PRIMARY KEY (ttr_idmantpo),
    CONSTRAINT fk_mantepotre_potrero FOREIGN KEY (ttr_idpotrer) REFERENCES public.ttrpotreros (ttr_idpotrer) ON DELETE CASCADE,
    CONSTRAINT fk_mantepotre_empleado FOREIGN KEY (ttr_responsable) REFERENCES public.ttrempleado (ttr_idemplo) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_mantepotre_potrero ON public.ttrmantepotre(ttr_idpotrer);
CREATE INDEX IF NOT EXISTS idx_mantepotre_fecha ON public.ttrmantepotre(ttr_fecha);

-- =====================================================
-- 3. ACTUALIZACIONES DE ESTRUCTURA (Lifecycle, Maintenance, ProdLeche, Clientes)
-- =====================================================

-- Lifecycle (schema_update_lifecycle.sql)
INSERT INTO TMAESTPOTRE (TMA_IDESTPO, TMA_NOMESTP) VALUES (16, 'En Recuperación') ON CONFLICT (TMA_IDESTPO) DO NOTHING;

ALTER TABLE IF EXISTS public.ttrrotacion
    ADD COLUMN IF NOT EXISTS ttr_dias_duracion INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ttr_fechafin_est DATE,
    ADD COLUMN IF NOT EXISTS ttr_fechafin_real DATE;

-- Maintenance (schema_update_maintenance.sql)
ALTER TABLE IF EXISTS public.ttrmantepotre ADD COLUMN IF NOT EXISTS ttr_fechafin DATE;
ALTER TABLE IF EXISTS public.ttrpotreros ADD COLUMN IF NOT EXISTS ttr_fecfinmnt DATE;

-- Producción Leche (schema_prodleche_v2.sql)
ALTER TABLE public.ttrprodlote ADD COLUMN IF NOT EXISTS ttr_jornada character varying(20) DEFAULT 'AM', ADD COLUMN IF NOT EXISTS ttr_observacion text;
ALTER TABLE public.ttrprodlech ADD COLUMN IF NOT EXISTS ttr_observacion text;

-- Clientes Soft Delete (schema_update_clientes_soft_delete.sql)
ALTER TABLE "ttrclienteee" ADD COLUMN IF NOT EXISTS "ttr_activo" BOOLEAN DEFAULT TRUE;

-- =====================================================
-- 4. MEJORAS BOVINOS Y GENEALOGÍA (Bovinos Enhanced + External Parents)
-- =====================================================

-- Columnas nuevas
ALTER TABLE ttrbovinoss ADD COLUMN IF NOT EXISTS ttr_sexo VARCHAR(10) CHECK (ttr_sexo IN ('Macho', 'Hembra'));
ALTER TABLE ttrbovinoss ADD COLUMN IF NOT EXISTS ttr_idpadre INTEGER REFERENCES ttrbovinoss(ttr_idbovino) ON DELETE SET NULL;
ALTER TABLE ttrbovinoss ADD COLUMN IF NOT EXISTS ttr_idmadre INTEGER REFERENCES ttrbovinoss(ttr_idbovino) ON DELETE SET NULL;
ALTER TABLE ttrbovinoss ADD COLUMN IF NOT EXISTS ttr_numpartos INTEGER DEFAULT 0;
ALTER TABLE ttrbovinoss ADD COLUMN IF NOT EXISTS ttr_fecultpar DATE;
ALTER TABLE ttrbovinoss ADD COLUMN IF NOT EXISTS ttr_padre_externo VARCHAR(100);
ALTER TABLE ttrbovinoss ADD COLUMN IF NOT EXISTS ttr_madre_externa VARCHAR(100);

CREATE INDEX IF NOT EXISTS idx_bovinos_padre ON ttrbovinoss(ttr_idpadre);
CREATE INDEX IF NOT EXISTS idx_bovinos_madre ON ttrbovinoss(ttr_idmadre);
CREATE INDEX IF NOT EXISTS idx_bovinos_sexo ON ttrbovinoss(ttr_sexo);

-- Comentarios
COMMENT ON COLUMN ttrbovinoss.ttr_sexo IS 'Sexo del bovino: Macho o Hembra';
COMMENT ON COLUMN ttrbovinoss.ttr_idpadre IS 'ID del bovino padre (sire)';
COMMENT ON COLUMN ttrbovinoss.ttr_idmadre IS 'ID del bovino madre (dam)';
COMMENT ON COLUMN ttrbovinoss.ttr_numpartos IS 'Número total de partos (solo hembras)';
COMMENT ON COLUMN ttrbovinoss.ttr_fecultpar IS 'Fecha del último parto (solo hembras)';
COMMENT ON COLUMN ttrbovinoss.ttr_padre_externo IS 'Nombre del padre (sire) si es externo a la finca';
COMMENT ON COLUMN ttrbovinoss.ttr_madre_externa IS 'Nombre de la madre (dam) si es externa a la finca';

-- Vista Genealogía Completa
CREATE OR REPLACE VIEW vw_bovinos_genealogia AS
SELECT 
    b.ttr_idbovino, b.ttr_numerobv, b.ttr_sexo, b.ttr_fecnacim, b.ttr_pesokilo, b.ttr_idestadb,
    p.ttr_numerobv AS padre_numero, p.ttr_idbovino AS padre_id, rp.tma_nomraza AS padre_raza,
    b.ttr_padre_externo,
    m.ttr_numerobv AS madre_numero, m.ttr_idbovino AS madre_id, rm.tma_nomraza AS madre_raza,
    b.ttr_madre_externa,
    b.ttr_numpartos, b.ttr_fecultpar, b.ttr_idpadre, b.ttr_idmadre,
    rb.tma_nomraza AS raza_nombre, cb.tma_nomcolb AS color_nombre,
    eb.tma_nometab AS etapa_nombre, esb.tma_nomestb AS estado_nombre
FROM ttrbovinoss b
LEFT JOIN ttrbovinoss p ON b.ttr_idpadre = p.ttr_idbovino
LEFT JOIN tmarazabovi rp ON p.ttr_idrazabo = rp.tma_idrazab
LEFT JOIN ttrbovinoss m ON b.ttr_idmadre = m.ttr_idbovino
LEFT JOIN tmarazabovi rm ON m.ttr_idrazabo = rm.tma_idrazab
LEFT JOIN tmarazabovi rb ON b.ttr_idrazabo = rb.tma_idrazab
LEFT JOIN tmacolbovin cb ON b.ttr_idcolorb = cb.tma_idcolbo
LEFT JOIN tmaetabovin eb ON b.ttr_idetapav = eb.tma_idetabo
LEFT JOIN tmaestbovin esb ON b.ttr_idestadb = esb.tma_idestbo;

COMMENT ON VIEW vw_bovinos_genealogia IS 'Vista que incluye información genealógica completa de cada bovino';

-- =====================================================
-- 5. MÓDULO DE VENTAS (schema_ventas.sql)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.ttrdetfactura (
    ttr_iddetfac INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idfactur INTEGER NOT NULL,
    ttr_tipoprod VARCHAR(20) NOT NULL,
    ttr_idproduc INTEGER NOT NULL,
    ttr_cantidad DECIMAL(10,2) NOT NULL,
    ttr_precunit DECIMAL(10,2) NOT NULL,
    ttr_subtotal DECIMAL(10,2) NOT NULL,
    ttr_descripcion TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrdetfactura_pkey PRIMARY KEY (ttr_iddetfac),
    CONSTRAINT fk_detfactura_factura FOREIGN KEY (ttr_idfactur) REFERENCES public.ttrfacturas (ttr_idfactur) ON DELETE CASCADE,
    CONSTRAINT chk_tipoprod CHECK (ttr_tipoprod IN ('INSUMO', 'BOVINO'))
);

ALTER TABLE public.ttrfacturas ALTER COLUMN ttr_idprodct DROP NOT NULL;
ALTER TABLE public.ttrfacturas ALTER COLUMN ttr_litrosfc DROP NOT NULL;
ALTER TABLE public.ttrfacturas ALTER COLUMN ttr_idregmdc DROP NOT NULL;

ALTER TABLE public.ttrfacturas
    ADD COLUMN IF NOT EXISTS ttr_subtotal DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS ttr_impuesto DECIMAL(10,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ttr_descuento DECIMAL(10,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ttr_observaciones TEXT,
    ADD COLUMN IF NOT EXISTS ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS ttr_fechupda TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.ttrinsumoso ADD COLUMN IF NOT EXISTS ttr_preciounit DECIMAL(10,2) DEFAULT 0;
ALTER TABLE public.ttrbovinoss ADD COLUMN IF NOT EXISTS ttr_precioventa DECIMAL(10,2) DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_detfactura_factura ON public.ttrdetfactura(ttr_idfactur);
CREATE INDEX IF NOT EXISTS idx_detfactura_tipo ON public.ttrdetfactura(ttr_tipoprod);
CREATE INDEX IF NOT EXISTS idx_detfactura_producto ON public.ttrdetfactura(ttr_idproduc);
CREATE INDEX IF NOT EXISTS idx_facturas_fecha ON public.ttrfacturas(ttr_fechafac);
CREATE INDEX IF NOT EXISTS idx_facturas_cliente ON public.ttrfacturas(ttr_idclient);
CREATE INDEX IF NOT EXISTS idx_facturas_estado ON public.ttrfacturas(ttr_idestfac);
CREATE INDEX IF NOT EXISTS idx_facturas_usuario ON public.ttrfacturas(ttr_idusuref);
CREATE INDEX IF NOT EXISTS idx_insumos_precio ON public.ttrinsumoso(ttr_preciounit);
CREATE INDEX IF NOT EXISTS idx_bovinos_precio ON public.ttrbovinoss(ttr_precioventa);

-- =====================================================
-- 6. MÓDULO SANITARIO (schema_sanidad.sql)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.ttrplanvacun
(
    ttr_idplanva INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_nomplan VARCHAR(100) NOT NULL,
    ttr_idtipvac INTEGER NOT NULL,
    ttr_fechaini DATE NOT NULL,
    ttr_fechafin DATE NOT NULL,
    ttr_intervalo INTEGER,
    ttr_numdosis INTEGER DEFAULT 1,
    ttr_descripcion TEXT,
    ttr_activo BOOLEAN DEFAULT TRUE,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ttr_fechupda TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrplanvacun_pkey PRIMARY KEY (ttr_idplanva),
    CONSTRAINT fk_planvacun_tipvac FOREIGN KEY (ttr_idtipvac) REFERENCES public.tmatipvacun (tma_idtipva)
);

CREATE TABLE IF NOT EXISTS public.ttrvacunacion
(
    ttr_idvacuna INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idbovino INTEGER NOT NULL,
    ttr_idplanva INTEGER,
    ttr_idtipvac INTEGER NOT NULL,
    ttr_fechaapl DATE NOT NULL,
    ttr_proxfech DATE,
    ttr_numdosis INTEGER DEFAULT 1,
    ttr_idempldo INTEGER,
    ttr_lote VARCHAR(50),
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrvacunacion_pkey PRIMARY KEY (ttr_idvacuna),
    CONSTRAINT fk_vacunacion_bovino FOREIGN KEY (ttr_idbovino) REFERENCES public.ttrbovinoss (ttr_idbovino) ON DELETE CASCADE,
    CONSTRAINT fk_vacunacion_plan FOREIGN KEY (ttr_idplanva) REFERENCES public.ttrplanvacun (ttr_idplanva) ON DELETE SET NULL,
    CONSTRAINT fk_vacunacion_tipvac FOREIGN KEY (ttr_idtipvac) REFERENCES public.tmatipvacun (tma_idtipva),
    CONSTRAINT fk_vacunacion_empleado FOREIGN KEY (ttr_idempldo) REFERENCES public.ttrempleado (ttr_idemplo) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.ttrprenez
(
    ttr_idprenez INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idbovino INTEGER NOT NULL,
    ttr_fechaini DATE NOT NULL,
    ttr_fechaestp DATE,
    ttr_fechareal DATE,
    ttr_estadopre VARCHAR(50),
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ttr_fechupda TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrprenez_pkey PRIMARY KEY (ttr_idprenez),
    CONSTRAINT fk_prenez_bovino FOREIGN KEY (ttr_idbovino) REFERENCES public.ttrbovinoss (ttr_idbovino) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.ttrtratprenez
(
    ttr_idtratpr INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idprenez INTEGER NOT NULL,
    ttr_idtratam INTEGER,
    ttr_fechaapl DATE NOT NULL,
    ttr_tipotrat VARCHAR(100),
    ttr_proxfech DATE,
    ttr_dosisnum INTEGER DEFAULT 1,
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrtratprenez_pkey PRIMARY KEY (ttr_idtratpr),
    CONSTRAINT fk_tratprenez_prenez FOREIGN KEY (ttr_idprenez) REFERENCES public.ttrprenez (ttr_idprenez) ON DELETE CASCADE,
    CONSTRAINT fk_tratprenez_trat FOREIGN KEY (ttr_idtratam) REFERENCES public.tmatratamen (tma_idtrata) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.ttrvisivete
(
    ttr_idvisvet INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_fechavis DATE NOT NULL,
    ttr_proxfech DATE,
    ttr_veterina VARCHAR(200),
    ttr_telefono VARCHAR(15),
    ttr_motivovi TEXT,
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ttr_fechupda TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrvisivete_pkey PRIMARY KEY (ttr_idvisvet)
);

CREATE TABLE IF NOT EXISTS public.ttrvisibovino
(
    ttr_idvisbov INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idvisvet INTEGER NOT NULL,
    ttr_idbovino INTEGER NOT NULL,
    ttr_diagnos TEXT,
    ttr_tratamie TEXT,
    ttr_estadore VARCHAR(100),
    ttr_observa TEXT,
    CONSTRAINT ttrvisibovino_pkey PRIMARY KEY (ttr_idvisbov),
    CONSTRAINT fk_visibovino_visita FOREIGN KEY (ttr_idvisvet) REFERENCES public.ttrvisivete (ttr_idvisvet) ON DELETE CASCADE,
    CONSTRAINT fk_visibovino_bovino FOREIGN KEY (ttr_idbovino) REFERENCES public.ttrbovinoss (ttr_idbovino) ON DELETE CASCADE
);

INSERT INTO public.tmatipvacun (tma_nomtipv) VALUES ('Aftosa Triple'), ('Aftosa + Clostridium'), ('Estomatitis'), ('Mastitis'), ('Brucelosis'), ('Rabia'), ('Carbón Sintomático'), ('IBR/DVB'), ('Leptospirosis') ON CONFLICT DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_vacunacion_bovino ON public.ttrvacunacion(ttr_idbovino);
CREATE INDEX IF NOT EXISTS idx_vacunacion_proxfech ON public.ttrvacunacion(ttr_proxfech);
CREATE INDEX IF NOT EXISTS idx_vacunacion_fechaapl ON public.ttrvacunacion(ttr_fechaapl);
CREATE INDEX IF NOT EXISTS idx_prenez_bovino ON public.ttrprenez(ttr_idbovino);
CREATE INDEX IF NOT EXISTS idx_prenez_estado ON public.ttrprenez(ttr_estadopre);
CREATE INDEX IF NOT EXISTS idx_tratprenez_prenez ON public.ttrtratprenez(ttr_idprenez);
CREATE INDEX IF NOT EXISTS idx_tratprenez_proxfech ON public.ttrtratprenez(ttr_proxfech);
CREATE INDEX IF NOT EXISTS idx_visivete_fechavis ON public.ttrvisivete(ttr_fechavis);
CREATE INDEX IF NOT EXISTS idx_visivete_proxfech ON public.ttrvisivete(ttr_proxfech);
CREATE INDEX IF NOT EXISTS idx_visibovino_bovino ON public.ttrvisibovino(ttr_idbovino);

COMMIT;
