CREATE TABLE TMAEMPLEADO (
  TMA_IDEMPLO SERIAL PRIMARY KEY,
  TMA_NOMBREL VARCHAR(100)
);

CREATE TABLE TMAROLUSUAR (
  TMA_IDROLUS SERIAL PRIMARY KEY,
  TMA_NOMROLU VARCHAR(50)
);

CREATE TABLE TMATIPCLIEN (
  TMA_IDTIPCL SERIAL PRIMARY KEY,
  TMA_NOMTIPC VARCHAR(50)
);

CREATE TABLE TMARAZABOVI (
  TMA_IDRAZAB SERIAL PRIMARY KEY,
  TMA_NOMRAZA VARCHAR(50)
);

CREATE TABLE TMACOLBOVIN (
  TMA_IDCOLBO SERIAL PRIMARY KEY,
  TMA_NOMCOLB VARCHAR(50)
);

CREATE TABLE TMAETABOVIN (
  TMA_IDETABO SERIAL PRIMARY KEY,
  TMA_NOMETAB VARCHAR(50)
);

CREATE TABLE TMAESTBOVIN (
  TMA_IDESTBO SERIAL PRIMARY KEY,
  TMA_NOMESTB VARCHAR(50)
);

CREATE TABLE TMACATINSUM (
  TMA_IDCATIN SERIAL PRIMARY KEY,
  TMA_NOMCATI VARCHAR(50)
);

CREATE TABLE TMATIPMOVIM (
  TMA_IDTIPMO SERIAL PRIMARY KEY,
  TMA_NOMTIPM VARCHAR(50)
);

CREATE TABLE TMATIPPAGOS (
  TMA_IDTIPPAG SERIAL PRIMARY KEY,
  TMA_NOMTIPP VARCHAR(50)
);

CREATE TABLE TMATRATAMEN (
  TMA_IDTRATA SERIAL PRIMARY KEY,
  TMA_NOMTRAT VARCHAR(50)
);

CREATE TABLE TMATIPVACUN (
  TMA_IDTIPVA SERIAL PRIMARY KEY,
  TMA_NOMTIPV VARCHAR(50)
);

CREATE TABLE TMATIPVENTA (
  TMA_IDTIPVE SERIAL PRIMARY KEY,
  TMA_NOMTIPV VARCHAR(50)
);

CREATE TABLE TMAESTFACTU (
  TMA_IDESTFA SERIAL PRIMARY KEY,
  TMA_NOMESTF VARCHAR(50)
);

CREATE TABLE TMAESTPOTRE (
  TMA_IDESTPO SERIAL PRIMARY KEY,
  TMA_NOMESTP VARCHAR(50)
);

CREATE TABLE TMATIPMANTE (
  TMA_IDTIPMA SERIAL PRIMARY KEY,
  TMA_NOMTIPM VARCHAR(50)
);

CREATE TABLE TTREMPLEADO (
  TTR_IDEMPLO SERIAL PRIMARY KEY,
  TTR_NOMBREL VARCHAR(100),
  TTR_NOMSEGU VARCHAR(100),
  TTR_APELLID VARCHAR(100),
  TTR_APESEGU VARCHAR(100),
  TTR_DOCUMEN VARCHAR(20),
  TTR_FECNACI DATE,
  TTR_TELEFON VARCHAR(20),
  TTR_DIRECCI TEXT,
  TTR_FECCONT DATE,
  TTR_IDCARGP INT REFERENCES TMAEMPLEADO(TMA_IDEMPLO),
  TTR_FECCREA TIMESTAMP,
  TTR_FECUPDA TIMESTAMP
);

CREATE TABLE TTRUSUARIOO (
  TTR_IDUSUAR VARCHAR(36) PRIMARY KEY,
  TTR_NOMBREL VARCHAR(100),
  TTR_APELLID VARCHAR(100),
  TTR_CORREOE VARCHAR(100),
  TTR_TELEFON VARCHAR(20),
  TTR_IDROLUS INT REFERENCES TMAROLUSUAR(TMA_IDROLUS)
);

CREATE TABLE TTRCLIENTEEE (
  TTR_IDCLIENT SERIAL PRIMARY KEY,
  TTR_TIPOCLIE INT REFERENCES TMATIPCLIEN(TMA_IDTIPCL),
  TTR_NOMCOMPA VARCHAR(100),
  TTR_NOMBRECL VARCHAR(100),
  TTR_APELLIDO VARCHAR(100),
  TTR_DOCUMECL VARCHAR(20),
  TTR_TELEFONO VARCHAR(20),
  TTR_DIRECCIO TEXT,
  TTR_CORREOCL VARCHAR(100)
);

CREATE TABLE TTRBOVINOSS (
  TTR_IDBOVINO SERIAL PRIMARY KEY,
  TTR_NUMEROBV INT,
  TTR_IDRAZABO INT REFERENCES TMARAZABOVI(TMA_IDRAZAB),
  TTR_FECNACIM DATE,
  TTR_IDCOLORB INT REFERENCES TMACOLBOVIN(TMA_IDCOLBO),
  TTR_PESOKILO FLOAT,
  TTR_IDETAPAV INT REFERENCES TMAETABOVIN(TMA_IDETABO),
  TTR_IDESTADB INT REFERENCES TMAESTBOVIN(TMA_IDESTBO)
);

CREATE TABLE TTRINSUMOSO (
  TTR_IDINSUMO SERIAL PRIMARY KEY,
  TTR_IDCATEIN INT REFERENCES TMACATINSUM(TMA_IDCATIN),
  TTR_NOMINSUM VARCHAR(100),
  TTR_CANTIDAD INT,
  TTR_FECHAVEN DATE
);

CREATE TABLE TTRMOVIMIEN (
  TTR_IDMOVIME SERIAL PRIMARY KEY,
  TTR_IDINSUMO INT REFERENCES TTRINSUMOSO(TTR_IDINSUMO),
  TTR_IDTIPMOV INT REFERENCES TMATIPMOVIM(TMA_IDTIPMO),
  TTR_CANTIMOV INT,
  TTR_FECHAMOV TIMESTAMP,
  TTR_FECHCREA TIMESTAMP,
  TTR_FECHUPDA TIMESTAMP
);

CREATE TABLE TTRPAGINSUM (
  TTR_IDPAGINS SERIAL PRIMARY KEY,
  TTR_IDINSUMP INT REFERENCES TTRINSUMOSO(TTR_IDINSUMO),
  TTR_MONTOPAG FLOAT,
  TTR_FECHAPAG TIMESTAMP,
  TTR_FECHCREA TIMESTAMP,
  TTR_FECHUPDA TIMESTAMP
);

CREATE TABLE TTRASISTENC (
  TTR_IDASISEN SERIAL PRIMARY KEY,
  TTR_IDEMPLEA INT REFERENCES TTREMPLEADO(TTR_IDEMPLO),
  TTR_HORAENTR TIME,
  TTR_HORASALI TIME,
  TTR_HORATRAB TIME,
  TTR_FECHAASI DATE
);

CREATE TABLE TTRNOMINASS (
  TTR_IDNOMINA SERIAL PRIMARY KEY,
  TTR_IDASISTE INT REFERENCES TTRASISTENC(TTR_IDASISEN),
  TTR_TOTHORAS FLOAT,
  TTR_TOTPAGOS FLOAT,
  TTR_FECHAINI DATE,
  TTR_FECHAFIN DATE,
  TTR_FECHCREA TIMESTAMP
);

CREATE TABLE TTREGRESOSS (
  TTR_IDEGRESO SERIAL PRIMARY KEY,
  TTR_IDEMPREG INT REFERENCES TTREMPLEADO(TTR_IDEMPLO),
  TTR_FECHPAGO DATE,
  TTR_IDTIPPAG INT REFERENCES TMATIPPAGOS(TMA_IDTIPPAG),
  TTR_IDNOMREF INT REFERENCES TTRNOMINASS(TTR_IDNOMINA),
  TTR_IDPAGREF INT REFERENCES TTRPAGINSUM(TTR_IDPAGINS),
  TTR_FECHCREA TIMESTAMP,
  TTR_FECHUPDA TIMESTAMP
);

CREATE TABLE TTRREGMEDIC (
  TTR_IDREGMED SERIAL PRIMARY KEY,
  TTR_IDBOVREF INT REFERENCES TTRBOVINOSS(TTR_IDBOVINO),
  TTR_IDEMPMED INT REFERENCES TTREMPLEADO(TTR_IDEMPLO),
  TTR_IDMOVREF INT REFERENCES TTRMOVIMIEN(TTR_IDMOVIME),
  TTR_DIAGNOST TEXT,
  TTR_IDTRATAM INT REFERENCES TMATRATAMEN(TMA_IDTRATA),
  TTR_IDVACUNA INT REFERENCES TMATIPVACUN(TMA_IDTIPVA),
  TTR_FECHAREG TIMESTAMP
);

CREATE TABLE TTRPRODLECH (
  TTR_IDPRODLC SERIAL PRIMARY KEY,
  TTR_IDBOVLEC INT REFERENCES TTRBOVINOSS(TTR_IDBOVINO),
  TTR_FECHAPRO DATE,
  TTR_LITRSPRD FLOAT
);

CREATE TABLE TTRFACTURAS (
  TTR_IDFACTUR SERIAL PRIMARY KEY,
  TTR_IDCLIENT INT REFERENCES TTRCLIENTEEE(TTR_IDCLIENT),
  TTR_IDUSUREF VARCHAR(36) REFERENCES TTRUSUARIOO(TTR_IDUSUAR),
  TTR_IDPRODCT INT REFERENCES TTRPRODLECH(TTR_IDPRODLC),
  TTR_FECHAFAC TIMESTAMP,
  TTR_IDTIPVEN INT REFERENCES TMATIPVENTA(TMA_IDTIPVE),
  TTR_LITROSFC FLOAT,
  TTR_IDREGMDC INT REFERENCES TTRREGMEDIC(TTR_IDREGMED),
  TTR_IDESTFAC INT REFERENCES TMAESTFACTU(TMA_IDESTFA),
  TTR_MONTOFAC FLOAT
);

CREATE TABLE TTRPOTREROS (
  TTR_IDPOTRER SERIAL PRIMARY KEY,
  TTR_CODPOTRE VARCHAR(20),
  TTR_IDESTPOT INT REFERENCES TMAESTPOTRE(TMA_IDESTPO),
  TTR_IDTIPMAN INT REFERENCES TMATIPMANTE(TMA_IDTIPMA),
  TTR_FECHAMNT DATE,
  TTR_DESCRIPC TEXT
);
