-- =====================================================
-- MIGRACIÓN: MÓDULO DE VENTAS COMPLETO
-- =====================================================
-- Este script modifica el schema existente para soportar
-- un sistema completo de ventas de insumos y bovinos
-- =====================================================

BEGIN;

-- =====================================================
-- 1. NUEVA TABLA: DETALLES DE FACTURA
-- =====================================================
-- Permite múltiples productos (insumos o bovinos) por factura

CREATE TABLE IF NOT EXISTS public.ttrdetfactura (
    ttr_iddetfac INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idfactur INTEGER NOT NULL,           -- FK a TTRFACTURAS
    ttr_tipoprod VARCHAR(20) NOT NULL,       -- 'INSUMO' o 'BOVINO'
    ttr_idproduc INTEGER NOT NULL,           -- ID del insumo o bovino
    ttr_cantidad DECIMAL(10,2) NOT NULL,     -- Cantidad vendida
    ttr_precunit DECIMAL(10,2) NOT NULL,     -- Precio unitario
    ttr_subtotal DECIMAL(10,2) NOT NULL,     -- Cantidad * Precio
    ttr_descripcion TEXT,                    -- Descripción del producto
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrdetfactura_pkey PRIMARY KEY (ttr_iddetfac),
    CONSTRAINT fk_detfactura_factura FOREIGN KEY (ttr_idfactur)
        REFERENCES public.ttrfacturas (ttr_idfactur)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT chk_tipoprod CHECK (ttr_tipoprod IN ('INSUMO', 'BOVINO'))
);

-- =====================================================
-- 2. MODIFICAR TABLA TTRFACTURAS
-- =====================================================
-- Hacer campos opcionales y agregar nuevos campos

-- Hacer campos opcionales (permitir NULL)
ALTER TABLE public.ttrfacturas
    ALTER COLUMN ttr_idprodct DROP NOT NULL,
    ALTER COLUMN ttr_litrosfc DROP NOT NULL,
    ALTER COLUMN ttr_idregmdc DROP NOT NULL;

-- Agregar nuevos campos si no existen
ALTER TABLE public.ttrfacturas
    ADD COLUMN IF NOT EXISTS ttr_subtotal DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS ttr_impuesto DECIMAL(10,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ttr_descuento DECIMAL(10,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ttr_observaciones TEXT,
    ADD COLUMN IF NOT EXISTS ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS ttr_fechupda TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- =====================================================
-- 3. AGREGAR PRECIO A INSUMOS
-- =====================================================
-- Permitir definir precio de venta para insumos

ALTER TABLE public.ttrinsumoso
    ADD COLUMN IF NOT EXISTS ttr_preciounit DECIMAL(10,2) DEFAULT 0;

-- Actualizar precios de insumos existentes con valores por defecto
UPDATE public.ttrinsumoso
SET ttr_preciounit = 100.00
WHERE ttr_preciounit = 0 OR ttr_preciounit IS NULL;

-- =====================================================
-- 4. AGREGAR PRECIO A BOVINOS
-- =====================================================
-- Permitir definir precio de venta para bovinos

ALTER TABLE public.ttrbovinoss
    ADD COLUMN IF NOT EXISTS ttr_precioventa DECIMAL(10,2) DEFAULT 0;

-- Actualizar precios de bovinos existentes con valores estimados
UPDATE public.ttrbovinoss
SET ttr_precioventa = CASE 
    WHEN ttr_idetapav = 3 THEN 5000.00  -- Vacas
    WHEN ttr_idetapav = 4 THEN 6000.00  -- Toros
    WHEN ttr_idetapav = 5 THEN 3000.00  -- Vaquillas
    WHEN ttr_idetapav = 2 THEN 2500.00  -- Novillos
    WHEN ttr_idetapav = 1 THEN 1000.00  -- Terneros
    ELSE 2000.00
END
WHERE ttr_precioventa = 0 OR ttr_precioventa IS NULL;

-- =====================================================
-- 5. ÍNDICES PARA OPTIMIZACIÓN
-- =====================================================

-- Índices para detalles de factura
CREATE INDEX IF NOT EXISTS idx_detfactura_factura ON public.ttrdetfactura(ttr_idfactur);
CREATE INDEX IF NOT EXISTS idx_detfactura_tipo ON public.ttrdetfactura(ttr_tipoprod);
CREATE INDEX IF NOT EXISTS idx_detfactura_producto ON public.ttrdetfactura(ttr_idproduc);

-- Índices para facturas
CREATE INDEX IF NOT EXISTS idx_facturas_fecha ON public.ttrfacturas(ttr_fechafac);
CREATE INDEX IF NOT EXISTS idx_facturas_cliente ON public.ttrfacturas(ttr_idclient);
CREATE INDEX IF NOT EXISTS idx_facturas_estado ON public.ttrfacturas(ttr_idestfac);
CREATE INDEX IF NOT EXISTS idx_facturas_usuario ON public.ttrfacturas(ttr_idusuref);

-- Índices para búsqueda de productos
CREATE INDEX IF NOT EXISTS idx_insumos_precio ON public.ttrinsumoso(ttr_preciounit);
CREATE INDEX IF NOT EXISTS idx_bovinos_precio ON public.ttrbovinoss(ttr_precioventa);

-- =====================================================
-- 6. COMENTARIOS EN TABLAS Y COLUMNAS
-- =====================================================

COMMENT ON TABLE public.ttrdetfactura IS 'Detalles de factura - Productos vendidos en cada factura';
COMMENT ON COLUMN public.ttrdetfactura.ttr_tipoprod IS 'Tipo de producto: INSUMO o BOVINO';
COMMENT ON COLUMN public.ttrdetfactura.ttr_idproduc IS 'ID del producto (insumo o bovino)';

COMMENT ON COLUMN public.ttrfacturas.ttr_subtotal IS 'Subtotal antes de impuestos y descuentos';
COMMENT ON COLUMN public.ttrfacturas.ttr_impuesto IS 'Monto de impuestos aplicados';
COMMENT ON COLUMN public.ttrfacturas.ttr_descuento IS 'Monto de descuento aplicado';
COMMENT ON COLUMN public.ttrfacturas.ttr_observaciones IS 'Observaciones adicionales de la factura';

COMMENT ON COLUMN public.ttrinsumoso.ttr_preciounit IS 'Precio unitario de venta del insumo';
COMMENT ON COLUMN public.ttrbovinoss.ttr_precioventa IS 'Precio de venta del bovino';

COMMIT;

-- =====================================================
-- FIN DE LA MIGRACIÓN
-- =====================================================
-- Ejecutar este script en la base de datos para habilitar
-- el módulo de ventas completo
-- =====================================================
