-- =====================================================
-- MÓDULO DE GESTIÓN AVANZADA DE POTREROS Y LOTES
-- =====================================================

BEGIN;

-- 1. Historial de Bovinos en Lotes
-- Permite rastrear la permanencia de un bovino en un lote y los cambios.
CREATE TABLE IF NOT EXISTS public.ttrhistbovlote
(
    ttr_idhistbl INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idbovino INTEGER NOT NULL,
    ttr_idlote INTEGER NOT NULL,
    ttr_fechaini DATE NOT NULL DEFAULT CURRENT_DATE,
    ttr_fechafin DATE,
    ttr_motivo VARCHAR(100), -- 'Cambio producción', 'Enfermedad', 'Secado', 'Ingreso', etc.
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrhistbovlote_pkey PRIMARY KEY (ttr_idhistbl),
    CONSTRAINT fk_histbovlote_bovino FOREIGN KEY (ttr_idbovino)
        REFERENCES public.ttrbovinoss (ttr_idbovino) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_histbovlote_lote FOREIGN KEY (ttr_idlote)
        REFERENCES public.tmalotes (tma_idlote) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

-- Índices para búsquedas rápidas de historial
CREATE INDEX IF NOT EXISTS idx_histbovlote_bovino ON public.ttrhistbovlote(ttr_idbovino);
CREATE INDEX IF NOT EXISTS idx_histbovlote_lote ON public.ttrhistbovlote(ttr_idlote);
CREATE INDEX IF NOT EXISTS idx_histbovlote_fechas ON public.ttrhistbovlote(ttr_fechaini, ttr_fechafin);


-- 2. Rotación de Potreros
-- Registra la ocupación de potreros por lotes con detalle de turno y estado del pasto.
CREATE TABLE IF NOT EXISTS public.ttrrotacion
(
    ttr_idrotaci INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idlote INTEGER NOT NULL,
    ttr_idpotrer INTEGER NOT NULL,
    ttr_fecha DATE NOT NULL,
    ttr_turno VARCHAR(20) NOT NULL, -- 'AM', 'PM', 'DIA_COMPLETO'
    ttr_alturain DECIMAL(5,2),      -- Altura entrada (cm)
    ttr_alturaout DECIMAL(5,2),     -- Altura salida (cm)
    ttr_observa TEXT,
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrrotacion_pkey PRIMARY KEY (ttr_idrotaci),
    CONSTRAINT fk_rotacion_lote FOREIGN KEY (ttr_idlote)
        REFERENCES public.tmalotes (tma_idlote) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_rotacion_potrero FOREIGN KEY (ttr_idpotrer)
        REFERENCES public.ttrpotreros (ttr_idpotrer) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_rotacion_potrero ON public.ttrrotacion(ttr_idpotrer);
CREATE INDEX IF NOT EXISTS idx_rotacion_fecha ON public.ttrrotacion(ttr_fecha);


-- 3. Mantenimiento de Potreros
-- Bitácora de actividades de mantenimiento (Riego, Fumigación, etc.)
CREATE TABLE IF NOT EXISTS public.ttrmantepotre
(
    ttr_idmantpo INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idpotrer INTEGER NOT NULL,
    ttr_tipo VARCHAR(50) NOT NULL,    -- 'Riego', 'Fumigacion', 'Fertilizacion', 'Cercas'
    ttr_fecha DATE NOT NULL,
    ttr_producto VARCHAR(100),        -- Nombre del insumo usado (si aplica)
    ttr_cantidad DECIMAL(10,2),       -- Cantidad aplicada
    ttr_observa TEXT,
    ttr_responsable INTEGER,          -- ID Empleado
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ttrmantepotre_pkey PRIMARY KEY (ttr_idmantpo),
    CONSTRAINT fk_mantepotre_potrero FOREIGN KEY (ttr_idpotrer)
        REFERENCES public.ttrpotreros (ttr_idpotrer) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_mantepotre_empleado FOREIGN KEY (ttr_responsable)
        REFERENCES public.ttrempleado (ttr_idemplo) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_mantepotre_potrero ON public.ttrmantepotre(ttr_idpotrer);
CREATE INDEX IF NOT EXISTS idx_mantepotre_fecha ON public.ttrmantepotre(ttr_fecha);

COMMIT;
