-- =====================================================
-- MIGRACIÓN: MÓDULO DE SANIDAD V2
-- Sistema de Controles Sanitarios con Tipos Configurables
-- =====================================================
-- Este script crea un sistema flexible para gestionar
-- diferentes tipos de controles sanitarios:
-- - Vacunación
-- - Control de Mastitis (con cuartos mamarios)
-- - Desparasitación
-- - Baño de Garrapatas
-- Y permite agregar nuevos tipos sin modificar el schema
-- =====================================================

BEGIN;

-- =====================================================
-- 1. TABLA MAESTRA: TIPOS DE CONTROL SANITARIO
-- =====================================================
-- Catálogo configurable de tipos de control

CREATE TABLE IF NOT EXISTS public.tmatipocontrol
(
    tma_idtipcon INT GENERATED BY DEFAULT AS IDENTITY,
    tma_codigo VARCHAR(50) NOT NULL UNIQUE,        -- Código único: 'VACUNACION', 'MASTITIS', etc.
    tma_nombre VARCHAR(100) NOT NULL,              -- Nombre para mostrar en UI
    tma_descrip TEXT,                              -- Descripción del tipo
    tma_requieredetalle BOOLEAN DEFAULT FALSE,     -- Si requiere tabla detalle adicional
    tma_color VARCHAR(20),                         -- Color para UI (primary, danger, success, etc.)
    tma_icono VARCHAR(50),                         -- Nombre del ícono CoreUI
    tma_activo BOOLEAN DEFAULT TRUE,               -- Si está activo
    tma_orden INTEGER,                             -- Orden de visualización
    
    CONSTRAINT tmatipocontrol_pkey PRIMARY KEY (tma_idtipcon)
);

-- Datos iniciales
INSERT INTO public.tmatipocontrol (tma_codigo, tma_nombre, tma_descrip, tma_requieredetalle, tma_color, tma_icono, tma_orden) VALUES
    ('VACUNACION', 'Vacunación', 'Aplicación de vacunas preventivas', FALSE, 'primary', 'cilMedicalCross', 1),
    ('MASTITIS', 'Control de Mastitis', 'Revisión y tratamiento de cuartos mamarios', TRUE, 'danger', 'cilHeart', 2),
    ('DESPARASITACION', 'Desparasitación', 'Aplicación de desparasitantes internos y externos', FALSE, 'success', 'cilBug', 3),
    ('BANO_GARRAPATAS', 'Baño de Garrapatas', 'Tratamiento antiparasitario externo contra garrapatas', FALSE, 'warning', 'cilWater', 4)
ON CONFLICT (tma_codigo) DO NOTHING;

-- =====================================================
-- 2. TABLA GENÉRICA: CONTROLES SANITARIOS
-- =====================================================
-- Registra TODOS los tipos de controles sanitarios
-- Contiene campos comunes a cualquier tipo de control

CREATE TABLE IF NOT EXISTS public.ttrcontrolsanit
(
    ttr_idcontsa INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idbovino INTEGER NOT NULL,                 -- FK al bovino
    ttr_idtipcon INTEGER NOT NULL,                 -- FK al tipo de control
    ttr_fechacon DATE NOT NULL,                    -- Fecha del control
    
    -- Campos comunes a todos los controles
    ttr_idempldo INTEGER,                          -- Empleado responsable
    ttr_producto VARCHAR(200),                     -- Producto/vacuna/medicamento usado
    ttr_lote VARCHAR(50),                          -- Lote del producto
    ttr_dosis VARCHAR(50),                         -- Dosis aplicada (ej: "2 ml", "1 tableta")
    ttr_viaadmin VARCHAR(50),                      -- Vía: Oral, Inyectable, Tópico, Intramamaria
    ttr_resultado VARCHAR(100),                    -- Resultado/Estado (ej: Exitoso, Pendiente, etc.)
    ttr_proxfech DATE,                             -- Próximo control/refuerzo
    ttr_observa TEXT,                              -- Observaciones generales
    
    ttr_fechcrea TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ttr_fechupda TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT ttrcontrolsanit_pkey PRIMARY KEY (ttr_idcontsa),
    CONSTRAINT fk_controlsanit_bovino FOREIGN KEY (ttr_idbovino)
        REFERENCES public.ttrbovinoss (ttr_idbovino)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_controlsanit_tipo FOREIGN KEY (ttr_idtipcon)
        REFERENCES public.tmatipocontrol (tma_idtipcon)
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT fk_controlsanit_empleado FOREIGN KEY (ttr_idempldo)
        REFERENCES public.ttrempleado (ttr_idemplo)
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

-- =====================================================
-- 3. TABLA DETALLE: MASTITIS
-- =====================================================
-- Campos específicos para controles de mastitis
-- Incluye checkboxes de cuartos mamarios afectados

CREATE TABLE IF NOT EXISTS public.ttrmastitisdetalle
(
    ttr_idmastde INT GENERATED BY DEFAULT AS IDENTITY,
    ttr_idcontsa INTEGER NOT NULL,                 -- FK al control sanitario principal
    
    -- ¡Los famosos checkboxes de cuartos mamarios! 🐄
    ttr_cuarto1 BOOLEAN DEFAULT FALSE,             -- 1□ Cuarto Anterior Derecho
    ttr_cuarto2 BOOLEAN DEFAULT FALSE,             -- 2□ Cuarto Anterior Izquierdo  
    ttr_cuarto3 BOOLEAN DEFAULT FALSE,             -- 3□ Cuarto Posterior Derecho
    ttr_cuarto4 BOOLEAN DEFAULT FALSE,             -- 4□ Cuarto Posterior Izquierdo
    
    ttr_gravedad VARCHAR(50),                      -- Leve, Moderada, Severa
    ttr_tipomast VARCHAR(100),                     -- Clínica, Subclínica, Crónica
    ttr_trataesp TEXT,                             -- Tratamiento específico aplicado
    
    CONSTRAINT ttrmastitisdetalle_pkey PRIMARY KEY (ttr_idmastde),
    CONSTRAINT fk_mastitisdet_control FOREIGN KEY (ttr_idcontsa)
        REFERENCES public.ttrcontrolsanit (ttr_idcontsa)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT uk_mastitisdet_control UNIQUE (ttr_idcontsa)  -- Solo 1 detalle por control
);

-- =====================================================
-- 4. ÍNDICES PARA OPTIMIZACIÓN
-- =====================================================

-- Índices para tabla de controles sanitarios
CREATE INDEX IF NOT EXISTS idx_controlsanit_bovino ON public.ttrcontrolsanit(ttr_idbovino);
CREATE INDEX IF NOT EXISTS idx_controlsanit_tipo ON public.ttrcontrolsanit(ttr_idtipcon);
CREATE INDEX IF NOT EXISTS idx_controlsanit_fecha ON public.ttrcontrolsanit(ttr_fechacon);
CREATE INDEX IF NOT EXISTS idx_controlsanit_proxfech ON public.ttrcontrolsanit(ttr_proxfech);
CREATE INDEX IF NOT EXISTS idx_controlsanit_empleado ON public.ttrcontrolsanit(ttr_idempldo);

-- Índices para detalle de mastitis
CREATE INDEX IF NOT EXISTS idx_mastitisdet_control ON public.ttrmastitisdetalle(ttr_idcontsa);

-- Índice para tipos de control activos
CREATE INDEX IF NOT EXISTS idx_tipocontrol_activo ON public.tmatipocontrol(tma_activo);
CREATE INDEX IF NOT EXISTS idx_tipocontrol_orden ON public.tmatipocontrol(tma_orden);

-- =====================================================
-- 5. COMENTARIOS EN TABLAS Y COLUMNAS
-- =====================================================

COMMENT ON TABLE public.tmatipocontrol IS 'Catálogo de tipos de control sanitario (vacunación, mastitis, desparasitación, etc.)';
COMMENT ON COLUMN public.tmatipocontrol.tma_requieredetalle IS 'Indica si el tipo requiere tabla detalle adicional (ej: mastitis con cuartos)';

COMMENT ON TABLE public.ttrcontrolsanit IS 'Registro de todos los controles sanitarios realizados a bovinos';
COMMENT ON COLUMN public.ttrcontrolsanit.ttr_proxfech IS 'Fecha del próximo control o refuerzo';

COMMENT ON TABLE public.ttrmastitisdetalle IS 'Detalles específicos de controles de mastitis - cuartos mamarios afectados';
COMMENT ON COLUMN public.ttrmastitisdetalle.ttr_cuarto1 IS 'Cuarto Anterior Derecho afectado';
COMMENT ON COLUMN public.ttrmastitisdetalle.ttr_cuarto2 IS 'Cuarto Anterior Izquierdo afectado';
COMMENT ON COLUMN public.ttrmastitisdetalle.ttr_cuarto3 IS 'Cuarto Posterior Derecho afectado';
COMMENT ON COLUMN public.ttrmastitisdetalle.ttr_cuarto4 IS 'Cuarto Posterior Izquierdo afectado';

COMMIT;

-- =====================================================
-- VERIFICACIÓN
-- =====================================================
-- Ejecutar estos comandos para verificar que las tablas se crearon correctamente:
--
-- \dt ttrcontrolsanit
-- \dt tmatipocontrol
-- \dt ttrmastitisdetalle
-- \d+ ttrcontrolsanit
-- \d+ ttrmastitisdetalle
--
-- SELECT * FROM tmatipocontrol ORDER BY tma_orden;
-- =====================================================
-- FIN DE LA MIGRACIÓN
-- =====================================================
